#!/usr/bin/env bash
# Create workflows (programmatic) + lead scoring property + sorted list.
# Workflow API limitations are real — for unsupported actions, log to manual-steps.json.
#
# Usage: 07-workflows.sh <customer-slug>

source "$(dirname "$0")/lib.sh"
load_env

SLUG="${1:-}"
[[ -n "$SLUG" ]] || fail "Usage: 07-workflows.sh <slug>"

WORK="$(work_dir "$SLUG")"
PLAN="$WORK/build-plan.json"
MANIFEST="$WORK/manifest.json"
PORTAL=$(sandbox_portal_id)

# ---- Lead scoring (if relevant) ----
HAS_LEAD_SCORING=$(python3 -c "
import json
plan = json.load(open('$PLAN'))
print('yes' if plan.get('lead_scoring') else 'no')
")

if [[ "$HAS_LEAD_SCORING" == "yes" ]]; then
  info "Setting up lead scoring..."

  # Create demo_lead_score property
  prop_body=$(cat <<'JSON'
{
  "name": "demo_lead_score",
  "label": "Demo Lead Score",
  "type": "number",
  "fieldType": "number",
  "groupName": "contactinformation",
  "description": "Lead score generated by hubspot-demo-prep skill"
}
JSON
)
  hs_curl POST "/crm/v3/properties/contacts" "$prop_body" >/dev/null
  if [[ "$HS_LAST_STATUS" =~ ^(2|409) ]]; then
    ok "  demo_lead_score property ready"
  fi

  # Backfill scores on existing contacts based on activity
  # Simple heuristic: count engagements per contact, score = count * 5 + random
  CONTACTS=$(python3 -c "
import json
m = json.load(open('$MANIFEST'))
print(' '.join(m.get('contacts', {}).values()))
")
  for cid in $CONTACTS; do
    score=$((RANDOM % 80 + 20))  # 20-100
    score_body="{\"properties\":{\"demo_lead_score\":\"$score\"}}"
    hs_curl PATCH "/crm/v3/objects/contacts/$cid" "$score_body" >/dev/null
  done
  ok "  Backfilled lead scores on $(echo $CONTACTS | wc -w | xargs) contacts"

  # Create a list view sorted by demo_lead_score (MANUAL list of top scorers)
  list_body=$(cat <<JSON
{
  "name": "Demo: Hot leads by score ($SLUG)",
  "objectTypeId": "0-1",
  "processingType": "MANUAL"
}
JSON
)
  resp=$(hs_curl POST "/crm/v3/lists" "$list_body")
  if [[ "$HS_LAST_STATUS" =~ ^2 ]]; then
    LIST_ID=$(echo "$resp" | python3 -c "import json, sys; d=json.load(sys.stdin); print(d.get('list', {}).get('listId') or d.get('listId') or d.get('id', ''))")
    ok "  Hot leads list created ($LIST_ID)"
    manifest_add "$SLUG" "lead_scoring" "list_id" "$LIST_ID"
    manifest_add "$SLUG" "lead_scoring" "list_url" "https://app.hubspot.com/contacts/$PORTAL/objects/0-1/views/$LIST_ID/list"

    # Add top-scoring contacts to the list (top 5 by score)
    TOP_IDS=$(python3 -c "
import json
m = json.load(open('$MANIFEST'))
ids = list(m.get('contacts', {}).values())[:5]
print(json.dumps(ids))
")
    add_body="{\"recordIdsToAdd\":$TOP_IDS}"
    hs_curl PUT "/crm/v3/lists/$LIST_ID/memberships/add" "$add_body" >/dev/null
  else
    warn "  Hot leads list creation failed (HTTP $HS_LAST_STATUS)"
  fi

  manifest_add "$SLUG" "lead_scoring" "property" "demo_lead_score"
fi

# ---- Workflows ----
WORKFLOW_COUNT=$(python3 -c "
import json
plan = json.load(open('$PLAN'))
print(len(plan.get('workflows', [])))
")

if [[ "$WORKFLOW_COUNT" -gt 0 ]]; then
  info "Creating $WORKFLOW_COUNT workflow(s)..."

  python3 -c "
import json
flows = json.load(open('$PLAN'))['workflows']
for f in flows:
    print(json.dumps(f))
" > "$WORK/workflows-list.json"

  while read -r flow_json; do
    flow_name=$(echo "$flow_json" | python3 -c "import json, sys; print(json.load(sys.stdin)['name'])")

    # Build a minimal but valid v4 flow body
    body=$(echo "$flow_json" | python3 -c "
import json, sys, uuid
f = json.load(sys.stdin)

# Build action graph from supported steps
actions = []
gaps = []
for i, step in enumerate(f.get('steps', [])):
    action_id = str(uuid.uuid4())
    if step['type'] == 'set_property':
        actions.append({
            'actionId': action_id,
            'type': 'SINGLE_CONNECTION',
            'actionTypeVersion': 0,
            'actionTypeId': '0-2',
            'fields': {
                'property_name': step['property'],
                'value': step['value']
            }
        })
    elif step['type'] == 'delay':
        actions.append({
            'actionId': action_id,
            'type': 'SINGLE_CONNECTION',
            'actionTypeVersion': 0,
            'actionTypeId': '0-1',
            'fields': {'delta': step.get('seconds', 86400), 'time_unit': 'SECONDS'}
        })
    elif step['type'] in ('send_email', 'send_sms', 'ai_step'):
        gaps.append({
            'workflow': f['name'],
            'step_index': i,
            'unsupported_action': step['type'],
            'description': step.get('description', '')
        })

body = {
    'type': 'CONTACT_FLOW',
    'name': f['name'],
    'enabled': False,  # Don't auto-enable; rep enables when demoing
    'actions': actions,
    'startActionId': actions[0]['actionId'] if actions else None
}
print(json.dumps({'flow': body, 'gaps': gaps}))
")

    flow_body=$(echo "$body" | python3 -c "import json, sys; print(json.dumps(json.load(sys.stdin)['flow']))")
    gaps=$(echo "$body" | python3 -c "import json, sys; print(json.dumps(json.load(sys.stdin)['gaps']))")

    resp=$(hs_curl POST "/automation/v4/flows" "$flow_body")
    if [[ "$HS_LAST_STATUS" =~ ^2 ]]; then
      flow_id=$(echo "$resp" | python3 -c "import json, sys; d=json.load(sys.stdin); print(d.get('id') or d.get('flowId', ''))")
      ok "  Workflow created: $flow_name (id=$flow_id)"
      manifest_add "$SLUG" "workflows" "$flow_name" "$flow_id"
      manifest_add "$SLUG" "workflow_urls" "$flow_name" "https://app.hubspot.com/workflows/$PORTAL/platform/flow/$flow_id/edit"
    else
      warn "  Workflow creation failed for $flow_name (HTTP $HS_LAST_STATUS): $resp"
      warn "  Logging as manual step"
      python3 -c "
import json, os
ms_path = '$WORK/manual-steps.json'
existing = json.load(open(ms_path)) if os.path.exists(ms_path) else []
existing.append({
    'item': 'Workflow: $flow_name',
    'reason': 'API workflow creation failed — build in UI for demo',
    'ui_url': 'https://app.hubspot.com/workflows/$PORTAL',
    'instructions': 'Build workflow named: $flow_name'
})
json.dump(existing, open(ms_path, 'w'), indent=2)
"
    fi

    # Log gaps even if workflow succeeded
    if [[ "$gaps" != "[]" ]]; then
      python3 -c "
import json, os
ms_path = '$WORK/manual-steps.json'
existing = json.load(open(ms_path)) if os.path.exists(ms_path) else []
gaps = json.loads('''$gaps''')
for g in gaps:
    existing.append({
        'item': f'Add {g[\"unsupported_action\"]} action to workflow \"{g[\"workflow\"]}\"',
        'reason': f'API does not support {g[\"unsupported_action\"]} — UI required',
        'ui_url': 'https://app.hubspot.com/workflows/$PORTAL',
        'instructions': g.get('description', '')
    })
json.dump(existing, open(ms_path, 'w'), indent=2)
"
    fi
  done < "$WORK/workflows-list.json"
fi

ok "Workflows phase complete for $SLUG"
manifest_add "$SLUG" "_meta" "phase_3_workflows_done" "true"
